import fileDownload from 'js-file-download'
import qs from 'qs'
import { createVideoWarningApi } from '@link/warning-feature/video-warning'
import {
  axiosParams,
  axiosPost,
  createAxiosFromStore,
  createFormDataAxios,
} from '../common/utils'

const api = createVideoWarningApi({
  axiosParams,
  axiosPost,
  createAxiosFromStore,
  createFormDataAxios,
  qs,
  fileDownload,
  createFormData: () => new FormData(),
})

export const {
  getWarningTypeList,
  getWarningTypeListAllTenant,
  addCamera,
  deleteCamera,
  batchDeleteCamera,
  cameraList,
  exportCameraList,
  downloadCameraTemplate,
  importCameraList,
  clientWarningList,
  clientWarningAudit,
  maintenanceWarningAudit,
  maintenanceWarningList,
  machineList,
  addMachine,
  deleteMachine,
  allMachineList,
  allWarningList,
  allWarningAudit,
  machineIndustryList,
  machineCompanyList,
  machineRegionList,
  machineProvinceList,
  warningStatusList,
  machineTypeYear,
  machineRank,
  saveOrUpdateAiSkill,
  deleteAiAuditSkill,
  aiAuditSkillList,
  videoModelSkillGlobalQuery,
  deleteVideoModelSkillGlobal,
  saveOrUpdateVideoModelSkillGlobal,
  videoModelSkillTenantQuery,
  deleteVideoModelSkillTenant,
  saveOrUpdateVideoModelSkillTenant,
  attentionAlarm,
  batchAttentionAlarm,
  batchAttentionAlarmInternal,
  exportWarningData,
  exportWarningTrend,
  exportWarningProcess,
  exportOrgWarning,
  exportPointWarning,
  exportWarningType,
  exportWarningLevel,
  saveOrUpdateVideoSiren,
  deleteVideoSiren,
  queryVideoSiren,
  batchDeleteWarningProcess,
  uploadWarningImage,
  queryWarningDetailById,
  saveOrUpdateCardSiren,
  queryCardSiren,
  deleteCardSiren,
} = api
