export const scceptanceList = [
  {
    applyId: '',
    id: '',
    title: '1、立项审批',
    checkContent: '1.1部门级',
    workAsk: '部门安全员评审,意见得到落实',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '1、立项审批',
    checkContent: '1.2公司级(工厂级)',
    workAsk: '公司安全员评审,意见得到落实',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '1、立项审批',
    checkContent: '1.3集团级',
    workAsk: '集团安全员评审,意见得到落实(如果需要)',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '2、设备本质安全',
    checkContent: '2.1危险部位',
    workAsk: '危险部位有防护,未凸现出来构成安全隐患',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '2、设备本质安全',
    checkContent: '2.2安全联锁',
    workAsk: '具备安全联锁功能,危险部位有机械互锁和安全门联锁',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '2、设备本质安全',
    checkContent: '2.3安全标识',
    workAsk: '危险部位和区域有安全警示标识',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '3、制度规范',
    checkContent: '3.1操作规程和安全规程',
    workAsk: '从说明书转换成适用的操作规程和安全规程',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '3、制度规范',
    checkContent: '3.2危险源辨识',
    workAsk: '形成危险源辨识清单,无漏辨识',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '3、制度规范',
    checkContent: '3.3培训',
    workAsk:
      '对相关操作、维修、管理人员组织开展工艺、设备、危险源控制方面的理论和现场培训,提供培训记录',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '4、职业健康',
    checkContent: '4.1噪声',
    workAsk: '了解厂家设计噪声限值,实测现场噪声值,不得超过800dB(A)',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '4、职业健康',
    checkContent: '4.2粉尘',
    workAsk: '又分成回收装置,没有粉尘泄露到现场和空气中,造成职业病隐患',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '4、职业健康',
    checkContent: '4.3温度',
    workAsk: '设备运行不产生高温现场温度不超多33℃,不低于5℃',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '4、职业健康',
    checkContent: '4.4湿度',
    workAsk: '湿度不大于70%,不低于30%',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '5、消防',
    checkContent: '5.1火灾隐患',
    workAsk: '工艺装备运行不产生火灾隐患',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '5、消防',
    checkContent: '5.2消防器材',
    workAsk: '现场配备足够的消防器材',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '5、消防',
    checkContent: '5.3资质',
    workAsk: '消防设计资质合格,消防器材和供应厂家资质合格',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '6、其他项目',
    checkContent: '6.1雷电',
    workAsk: '防雷防静电设施有效',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '6、其他项目',
    checkContent: '6.2特种设备',
    workAsk: '厂家及安装单位资质齐全有效,报装记录有效',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '6、其他项目',
    checkContent: '6.3特种作业人员',
    workAsk: '所需特种作业人员持证上岗',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '6、其他项目',
    checkContent: '6.4射线',
    workAsk: '现场没有紫外光及其他射线照射',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '7、记录和档案',
    checkContent: '7.1安全运行记录',
    workAsk: '建立了必要的安全运行记录',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '7、记录和档案',
    checkContent: '7.2安全资质材料',
    workAsk: '安全资质材料齐全且在安全部门建档备案',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
  {
    applyId: '',
    id: '',
    title: '7、记录和档案',
    checkContent: '7.3整改记录',
    workAsk: '安全整改记录完整有效',
    conditionType: 0,
    checkQuestionDTOS: [],
  },
]
